version: '3.8'

services:
  front:
    image: node:14
    container_name: fatec-frontend
    ports:
      - 8081:8080
    volumes:
      - $PWD:/app
      - $PWD/entrypoint.sh:/entrypoint.sh
    working_dir: /app
    entrypoint: /entrypoint.sh
    command:
      - npm
      - run
      - serve

networks:
  default:
    external:
      name: fatec-lab-dev-5_default
